### ISSUE TITLE
running zek on lisperati1000 - binary?

### ISSUE THREAD

**Issue by jhonny007** [drcode/zek#4]
have you used zek on the lisperati (raspberry zero)?
I could not install zig in one  of my environments sucessfully - so I was not able to build a binary for rasperry zero.
Can you provide a binary for it, please?

**Comment by drcode** [comment]
Yes I have done this, unfortunately it was on an older version of zek and I wiped out that legacy repo during some house cleaning :(

I will try to get around to supplying a binary for rasbpi when I can. You just have to add another couple of rows to `build-crossplatform.sh` with the right zig compile flag to generate the right ARM code, but unfortunately I forgot the flag name and couldn't find it with a quick google search.

**Comment by jhonny007** [comment]
Thank you for the quick reply. I could fix it myself and created a pull request.
